#!/usr/bin/env python3
"""Regenerate workbench.html for a gauntlet run from state files.

Reads run.json, pieces.json, lanes.json, cost.json, sessions/sessions.json,
and recent rounds/<piece>/<nnn>/gap.md files. Writes a self-contained static
HTML page (no external assets, simple responsive CSS) to
<run-dir>/workbench.html showing: the run status header, per-lane and
per-piece tables, the last three gaps per active piece, the latest inspection
excerpts where small text files exist, budget spent, and the distance to each
stop condition.

This page is generated by script only. No agent hand-authors it (SPEC 11.6).

Exit codes: 0 success, 1 validation failure, 2 usage error.
"""

import argparse
import html
import json
import os
import sys
from datetime import datetime, timezone

DEFAULT_BUDGETS = {
    "rounds_cap_per_piece": 10,
    "wave_cap": 4,
    "wall_clock_hours_per_session": 6,
    "subagent_cap_per_run": 400,
}

INSPECTION_TEXT_EXTS = {".txt", ".md", ".json", ".log", ".csv", ".out"}
INSPECTION_MAX_BYTES = 8192
EXCERPT_CHARS = 1500

CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font-family: -apple-system, system-ui, Helvetica, Arial, sans-serif;
       margin: 0 auto; padding: 1rem; max-width: 64rem; color: #111;
       background: #fff; line-height: 1.45; }
h1 { font-size: 1.3rem; margin: 0 0 0.25rem; }
h2 { font-size: 1.05rem; margin: 1.5rem 0 0.5rem; border-bottom: 1px solid #ccc;
     padding-bottom: 0.2rem; }
h3 { font-size: 0.95rem; margin: 1rem 0 0.3rem; }
.meta { color: #444; font-size: 0.85rem; margin-bottom: 0.75rem; }
.status { display: inline-block; padding: 0.1rem 0.5rem; border: 1px solid #111;
          border-radius: 0.75rem; font-size: 0.85rem; }
.wrap { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: 0.85rem; }
th, td { border: 1px solid #bbb; padding: 0.3rem 0.5rem; text-align: left;
         vertical-align: top; }
th { background: #f0f0f0; }
pre { background: #f6f6f6; border: 1px solid #ddd; padding: 0.5rem;
      overflow-x: auto; white-space: pre-wrap; word-break: break-word;
      font-size: 0.8rem; }
footer { margin-top: 2rem; color: #666; font-size: 0.75rem;
         border-top: 1px solid #ccc; padding-top: 0.5rem; }
@media (max-width: 600px) {
  body { padding: 0.5rem; }
  table { font-size: 0.75rem; }
  th, td { padding: 0.25rem 0.35rem; }
}
"""


def esc(value):
    if value is None:
        return "not recorded"
    return html.escape(str(value), quote=True)


def load_json(path, default=None):
    if not os.path.isfile(path):
        return default
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (ValueError, OSError):
        return default


def parse_ts(value):
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip()
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def as_number(value):
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value.strip())
        except ValueError:
            return None
    return None


def round_dirs(run_dir, piece_id):
    """Round directories for a piece, sorted oldest to newest."""
    base = os.path.join(run_dir, "rounds", str(piece_id))
    if not os.path.isdir(base):
        return []
    entries = [e for e in os.listdir(base) if os.path.isdir(os.path.join(base, e))]

    def key(name):
        return (0, int(name)) if name.isdigit() else (1, name)

    return [os.path.join(base, e) for e in sorted(entries, key=key)]


def recent_gaps(run_dir, piece_id, count=3):
    """Last `count` gaps for a piece, newest first, as (round_name, text)."""
    gaps = []
    for round_dir in reversed(round_dirs(run_dir, piece_id)):
        gap_path = os.path.join(round_dir, "gap.md")
        if not os.path.isfile(gap_path):
            continue
        try:
            with open(gap_path, "r", encoding="utf-8", errors="replace") as handle:
                text = handle.read().strip()
        except OSError:
            continue
        gaps.append((os.path.basename(round_dir), text or "not recorded"))
        if len(gaps) >= count:
            break
    return gaps


def latest_inspection_excerpts(run_dir, piece_id, limit=3):
    """Small text files from the newest round's inspection dir, as (name, excerpt)."""
    excerpts = []
    for round_dir in reversed(round_dirs(run_dir, piece_id)):
        inspection_dir = os.path.join(round_dir, "inspection")
        if not os.path.isdir(inspection_dir):
            continue
        for name in sorted(os.listdir(inspection_dir)):
            path = os.path.join(inspection_dir, name)
            if not os.path.isfile(path):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext not in INSPECTION_TEXT_EXTS:
                continue
            try:
                if os.path.getsize(path) > INSPECTION_MAX_BYTES:
                    continue
                with open(path, "r", encoding="utf-8", errors="replace") as handle:
                    text = handle.read()
            except OSError:
                continue
            excerpt = text.strip()
            if len(excerpt) > EXCERPT_CHARS:
                excerpt = excerpt[:EXCERPT_CHARS] + "\n[truncated]"
            excerpts.append(("%s/%s" % (os.path.basename(round_dir), name), excerpt))
            if len(excerpts) >= limit:
                return excerpts
        if excerpts:
            return excerpts
    return excerpts


def table(headers, rows):
    parts = ['<div class="wrap"><table><tr>']
    parts.extend("<th>%s</th>" % esc(h) for h in headers)
    parts.append("</tr>")
    if not rows:
        parts.append('<tr><td colspan="%d">not recorded</td></tr>' % len(headers))
    for row in rows:
        parts.append("<tr>" + "".join("<td>%s</td>" % cell for cell in row) + "</tr>")
    parts.append("</table></div>")
    return "".join(parts)


def fmt_num(value, digits=1):
    if value is None:
        return "unknown"
    if float(value).is_integer():
        return str(int(value))
    return ("%." + str(digits) + "f") % value


def stop_distance_rows(run_dir, run, pieces, budgets, cost, now):
    rows = []
    stop_flag = os.path.exists(os.path.join(run_dir, "STOP"))
    rows.append(("user stop flag", "present" if stop_flag else "absent",
                 "file STOP in run dir", "fires now" if stop_flag else "-"))

    looping = [p for p in pieces if p.get("status") == "looping"]

    win_dist = [max(0, 2 - int(as_number(p.get("consecutive_wins")) or 0)) for p in looping]
    rows.append(("piece converged (2 consecutive wins)",
                 "%d looping" % len(looping), "2 wins",
                 "closest piece needs %d more win(s)" % min(win_dist) if win_dist else "n/a"))

    default_cap = int(as_number(budgets.get("rounds_cap_per_piece")) or 10)
    round_dist = []
    for piece in looping:
        cap = int(as_number(piece.get("rounds_cap")) or default_cap)
        done = int(as_number(piece.get("rounds_completed")) or 0)
        round_dist.append(max(0, cap - done))
    rows.append(("round cap per piece", "%d looping" % len(looping),
                 str(default_cap) + " (default)",
                 "closest piece has %d round(s) left" % min(round_dist) if round_dist else "n/a"))

    gain_dist = [max(0, 2 - int(as_number(p.get("no_gain_streak")) or 0)) for p in looping]
    rows.append(("no-gain rule", "%d looping" % len(looping), "streak of 2",
                 "closest piece is %d repeat(s) away" % min(gain_dist) if gain_dist else "n/a"))

    wave_cap = int(as_number(budgets.get("wave_cap")) or 4)
    current_wave = int(as_number(run.get("current_wave")) or 1)
    rows.append(("wave cap", "wave %d" % current_wave, str(wave_cap),
                 "%d wave(s) remaining" % max(0, wave_cap - current_wave)))

    wall_limit = as_number(budgets.get("wall_clock_hours_per_session"))
    if wall_limit is None:
        wall_limit = float(DEFAULT_BUDGETS["wall_clock_hours_per_session"])
    sessions = (load_json(os.path.join(run_dir, "sessions", "sessions.json"), {}) or {}).get("sessions") or []
    open_session = None
    for session in reversed(sessions):
        if not session.get("exited"):
            open_session = session
            break
    if open_session is not None and parse_ts(open_session.get("entered")):
        elapsed = (now - parse_ts(open_session.get("entered"))).total_seconds() / 3600.0
        rows.append(("wall clock per session", "%sh elapsed" % fmt_num(elapsed),
                     "%sh" % fmt_num(wall_limit),
                     "%sh remaining" % fmt_num(max(0.0, wall_limit - elapsed))))
    else:
        rows.append(("wall clock per session", "no open session",
                     "%sh" % fmt_num(wall_limit), "n/a"))

    subagent_cap = int(as_number(budgets.get("subagent_cap_per_run")) or 400)
    subagents = as_number(cost.get("subagents_total"))
    rows.append(("subagent cap", fmt_num(subagents) if subagents is not None else "not recorded",
                 str(subagent_cap),
                 "%d remaining" % max(0, subagent_cap - int(subagents)) if subagents is not None else "unknown"))

    ceiling = as_number(budgets.get("cost_ceiling"))
    spent = as_number(cost.get("cost_spent"))
    if ceiling is not None and spent is not None:
        rows.append(("cost ceiling", fmt_num(spent, 2), fmt_num(ceiling, 2),
                     "%s remaining" % fmt_num(max(0.0, ceiling - spent), 2)))
    else:
        rows.append(("cost ceiling", str(cost.get("cost_spent", "not recorded")),
                     str(budgets.get("cost_ceiling", "not recorded")), "not tracked numerically"))
    return [tuple(esc(cell) for cell in row) for row in rows]


def build_html(run_dir, run, pieces, lanes_doc, cost, now):
    budgets = dict(DEFAULT_BUDGETS)
    budgets.update(run.get("budgets") or {})
    parts = []
    parts.append("<!DOCTYPE html>")
    parts.append('<html lang="en"><head><meta charset="utf-8">')
    parts.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    parts.append("<title>%s workbench</title>" % esc(run.get("run_id")))
    parts.append("<style>%s</style></head><body>" % CSS)

    # Run status header.
    parts.append("<h1>Gauntlet workbench: %s</h1>" % esc(run.get("run_id")))
    parts.append('<p class="meta"><span class="status">status: %s</span> '
                 "shape %s, domain %s, wave %s, stop reason %s</p>"
                 % (esc(run.get("status")), esc(run.get("execution_shape")),
                    esc(run.get("domain_primary")), esc(run.get("current_wave")),
                    esc(run.get("stop_reason") or "none")))
    parts.append('<p class="meta">Goal: %s</p>' % esc(run.get("goal_one_line")))

    # Lanes.
    parts.append("<h2>Lanes</h2>")
    lane_rows = []
    for lane in (lanes_doc.get("lanes") or []):
        lane_rows.append((esc(lane.get("id")), esc(lane.get("status")),
                          esc(lane.get("lock_holder")), esc(lane.get("heartbeat")),
                          esc(", ".join(lane.get("owned_pieces") or []) or "none"),
                          esc(", ".join(lane.get("owned_paths") or []) or "none")))
    parts.append(table(["lane", "status", "lock holder", "heartbeat",
                        "owned pieces", "owned paths"], lane_rows))

    # Pieces.
    parts.append("<h2>Pieces</h2>")
    default_cap = int(as_number(budgets.get("rounds_cap_per_piece")) or 10)
    piece_rows = []
    for piece in pieces:
        cap = int(as_number(piece.get("rounds_cap")) or default_cap)
        piece_rows.append((esc(piece.get("id")), esc(piece.get("name")),
                           esc(piece.get("lane")), esc(piece.get("wave")),
                           esc(piece.get("status")),
                           "%s / %s" % (esc(piece.get("rounds_completed", 0)), cap),
                           esc(piece.get("consecutive_wins", 0)),
                           esc(piece.get("no_gain_streak", 0)),
                           esc(piece.get("last_gap") or "none yet")))
    parts.append(table(["piece", "name", "lane", "wave", "status", "rounds",
                        "consecutive wins", "no-gain streak", "last gap"], piece_rows))

    # Last three gaps per active piece.
    parts.append("<h2>Recent gaps (last three per active piece)</h2>")
    active = [p for p in pieces if p.get("status") == "looping"]
    if not active:
        parts.append("<p>No pieces are currently looping.</p>")
    for piece in active:
        parts.append("<h3>%s</h3>" % esc(piece.get("id")))
        gaps = recent_gaps(run_dir, piece.get("id"))
        if not gaps:
            parts.append("<p>No gap files recorded yet.</p>")
        for round_name, text in gaps:
            parts.append("<p>Round %s:</p><pre>%s</pre>" % (esc(round_name), esc(text)))

    # Latest inspection excerpts.
    parts.append("<h2>Latest inspection excerpts</h2>")
    any_excerpt = False
    for piece in active:
        excerpts = latest_inspection_excerpts(run_dir, piece.get("id"))
        for label, text in excerpts:
            any_excerpt = True
            parts.append("<h3>%s: %s</h3><pre>%s</pre>"
                         % (esc(piece.get("id")), esc(label), esc(text)))
    if not any_excerpt:
        parts.append("<p>No small text inspection files found for active pieces.</p>")

    # Budget spent.
    parts.append("<h2>Budget spent</h2>")
    cost_rows = [(esc(key), esc(value)) for key, value in sorted(cost.items())] if cost else []
    parts.append(table(["metric", "value"], cost_rows))

    # Stop condition distances.
    parts.append("<h2>Stop condition distances</h2>")
    parts.append(table(["condition", "current", "limit", "distance"],
                       stop_distance_rows(run_dir, run, pieces, budgets, cost, now)))

    parts.append("<footer>Generated by render_workbench.py at %s from state files in %s. "
                 "This page is regenerated by script and never hand-authored.</footer>"
                 % (esc(now.strftime("%Y-%m-%dT%H:%M:%SZ")), esc(run_dir)))
    parts.append("</body></html>")
    return "\n".join(parts)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Regenerate workbench.html from gauntlet run state. Script-generated only.")
    parser.add_argument("--run-dir", required=True,
                        help="Path to .gauntlet/runs/<run-id>")
    args = parser.parse_args(argv)

    run_dir = os.path.abspath(args.run_dir)
    run = load_json(os.path.join(run_dir, "run.json"))
    if run is None:
        print(json.dumps({"ok": False, "reason": "run.json not found or unreadable in %s" % run_dir}))
        return 1

    pieces = (load_json(os.path.join(run_dir, "pieces.json"), {}) or {}).get("pieces") or []
    lanes_doc = load_json(os.path.join(run_dir, "lanes.json"), {}) or {}
    cost = load_json(os.path.join(run_dir, "cost.json"), {}) or {}
    now = datetime.now(timezone.utc)

    page = build_html(run_dir, run, pieces, lanes_doc, cost, now)
    out_path = os.path.join(run_dir, "workbench.html")
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(page)
    os.replace(tmp, out_path)

    print(json.dumps({"ok": True, "path": out_path,
                      "pieces": len(pieces),
                      "lanes": len(lanes_doc.get("lanes") or [])}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
